-module(debug_tests).


t1_test() ->
  Symtab = #{
    t9 =>
        {ty_scheme,[],
            {union,
                [
                  {fun_full,[{named,0,{ty_ref,'.',t9,0},[]}],{predef,any}},
                  {fun_full,[{predef,none}],{predef,any}}
                ]}}
  },

  
  global_state:with_new_state(fun() ->
    ty_parser:set_symtab(Symtab),
    %System = maps:keys(Symtab),
     
    Ty = {named, noloc, {ty_ref, '.', t9, 0}, []},
    Node = ty_parser:parse(Ty),

    io:format(user, "Check emptiness of ~p~n", [Node]),

    % emptiness
    ty_node:is_empty(Node),
    ty_node:is_empty(Node)

    % lists:foreach(fun(Name) -> 
    %   io:format(user, "Parsing ~p~n", [Name]),

    %   % parse
    %   Ty = {named, noloc, {ty_ref, '.', Name, 0}, []},
    %   Node = ty_parser:parse(Ty),

    %   io:format(user, "Check emptiness of ~p~n", [Node]),

    %   % emptiness
    %   ty_node:is_empty(Node),
    %   % cache
    %   ty_node:is_empty(Node)

    % end, System),
  end),
  ok.

slow_test() ->
System = 
#{t9 =>
      {intersection,
          [{fun_full,
               [{union,[{predef,any},{predef,none}]}],
               {union,
                   [{union,[{named,0,{ty_ref,'.',t8,0},[]},{predef,none}]},
                    {intersection,
                        [{predef,any},{named,0,{ty_ref,'.',t3,0},[]}]}]}},
           {union,[{predef,any},{predef,none}]}]},
  t1 =>
      {fun_full,
          [{fun_full,
               [{fun_full,
                    [{fun_full,
                         [{predef,none},
                          {predef,none},
                          {predef,any},
                          {predef,none},
                          {predef,none}],
                         {predef,none}}],
                    {union,[{predef,any},{predef,none}]}}],
               {predef,none}}],
          {intersection,
              [{predef,any},
               {fun_full,
                   [{fun_full,[{predef,any}],{predef,any}},
                    {union,[{named,0,{ty_ref,'.',t5,0},[]},{predef,any}]}],
                   {fun_full,
                       [{predef,any}],
                       {named,0,{ty_ref,'.',t8,0},[]}}}]}},
  t2 =>
      {fun_full,
          [{union,
               [{named,0,{ty_ref,'.',t3,0},[]},
                {union,
                    [{fun_full,
                         [{predef,any},
                          {predef,none},
                          {predef,none},
                          {named,0,{ty_ref,'.',t10,0},[]},
                          {predef,any},
                          {predef,none},
                          {named,0,{ty_ref,'.',t7,0},[]},
                          {predef,any},
                          {named,0,{ty_ref,'.',t1,0},[]},
                          {named,0,{ty_ref,'.',t9,0},[]},
                          {predef,any}],
                         {named,0,{ty_ref,'.',t1,0},[]}},
                     {union,
                         [{predef,none},{named,0,{ty_ref,'.',t7,0},[]}]}]}]},
           {intersection,
               [{fun_full,
                    [{predef,none},
                     {fun_full,[{predef,any}],{predef,none}},
                     {fun_full,
                         [{named,0,{ty_ref,'.',t8,0},[]},
                          {predef,none},
                          {predef,any},
                          {named,0,{ty_ref,'.',t8,0},[]},
                          {predef,any},
                          {named,0,{ty_ref,'.',t2,0},[]},
                          {named,0,{ty_ref,'.',t7,0},[]},
                          {predef,none},
                          {named,0,{ty_ref,'.',t5,0},[]}],
                         {named,0,{ty_ref,'.',t3,0},[]}},
                     {union,
                         [{named,0,{ty_ref,'.',t3,0},[]},
                          {named,0,{ty_ref,'.',t6,0},[]}]},
                     {predef,none},
                     {intersection,
                         [{named,0,{ty_ref,'.',t3,0},[]},
                          {named,0,{ty_ref,'.',t9,0},[]}]}],
                    {union,
                        [{named,0,{ty_ref,'.',t3,0},[]},
                         {named,0,{ty_ref,'.',t3,0},[]}]}},
                {intersection,
                    [{intersection,[{predef,any},{predef,any}]},
                     {intersection,[{predef,none},{predef,none}]}]}]},
           {union,
               [{predef,none},
                {intersection,
                    [{fun_full,[{predef,none}],{predef,none}},
                     {fun_full,[{predef,none}],{predef,any}}]}]},
           {fun_full,
               [{union,
                    [{named,0,{ty_ref,'.',t4,0},[]},
                     {intersection,[{predef,any},{predef,any}]}]}],
               {named,0,{ty_ref,'.',t9,0},[]}},
           {union,
               [{fun_full,
                    [{intersection,
                         [{named,0,{ty_ref,'.',t7,0},[]},
                          {named,0,{ty_ref,'.',t8,0},[]}]}],
                    {intersection,
                        [{predef,none},{named,0,{ty_ref,'.',t4,0},[]}]}},
                {fun_full,
                    [{predef,any}],
                    {intersection,
                        [{named,0,{ty_ref,'.',t7,0},[]},{predef,any}]}}]},
           {fun_full,
               [{fun_full,
                    [{fun_full,
                         [{predef,none}],
                         {named,0,{ty_ref,'.',t10,0},[]}}],
                    {predef,any}}],
               {predef,any}},
           {predef,none},
           {predef,any},
           {intersection,
               [{fun_full,
                    [{fun_full,
                         [{predef,any},
                          {predef,any},
                          {named,0,{ty_ref,'.',t6,0},[]},
                          {predef,any},
                          {named,0,{ty_ref,'.',t7,0},[]},
                          {named,0,{ty_ref,'.',t6,0},[]},
                          {named,0,{ty_ref,'.',t7,0},[]}],
                         {named,0,{ty_ref,'.',t6,0},[]}}],
                    {predef,any}},
                {fun_full,
                    [{intersection,
                         [{named,0,{ty_ref,'.',t3,0},[]},
                          {named,0,{ty_ref,'.',t7,0},[]}]}],
                    {fun_full,
                        [{named,0,{ty_ref,'.',t5,0},[]}],
                        {predef,none}}}]},
           {intersection,
               [{intersection,
                    [{fun_full,[{predef,none}],{predef,none}},
                     {named,0,{ty_ref,'.',t7,0},[]}]},
                {union,
                    [{union,[{named,0,{ty_ref,'.',t6,0},[]},{predef,any}]},
                     {intersection,[{predef,none},{predef,none}]}]}]},
           {intersection,
               [{intersection,
                    [{intersection,
                         [{predef,any},{named,0,{ty_ref,'.',t8,0},[]}]},
                     {predef,none}]},
                {intersection,
                    [{predef,any},
                     {fun_full,
                         [{named,0,{ty_ref,'.',t2,0},[]}],
                         {predef,none}}]}]},
           {union,
               [{union,
                    [{fun_full,[{named,0,{ty_ref,'.',t7,0},[]}],{predef,none}},
                     {intersection,
                         [{predef,any},{named,0,{ty_ref,'.',t4,0},[]}]}]},
                {intersection,
                    [{union,[{named,0,{ty_ref,'.',t3,0},[]},{predef,none}]},
                     {intersection,[{predef,any},{predef,any}]}]}]},
           {union,
               [{fun_full,
                    [{predef,none}],
                    {union,[{predef,none},{named,0,{ty_ref,'.',t1,0},[]}]}},
                {fun_full,
                    [{fun_full,
                         [{named,0,{ty_ref,'.',t3,0},[]},
                          {named,0,{ty_ref,'.',t1,0},[]},
                          {named,0,{ty_ref,'.',t3,0},[]},
                          {named,0,{ty_ref,'.',t3,0},[]},
                          {named,0,{ty_ref,'.',t5,0},[]},
                          {predef,none},
                          {predef,any},
                          {predef,none},
                          {predef,none},
                          {predef,any},
                          {named,0,{ty_ref,'.',t10,0},[]},
                          {named,0,{ty_ref,'.',t8,0},[]},
                          {predef,any},
                          {named,0,{ty_ref,'.',t8,0},[]},
                          {predef,none},
                          {named,0,{ty_ref,'.',t5,0},[]}],
                         {predef,any}}],
                    {union,[{named,0,{ty_ref,'.',t10,0},[]},{predef,any}]}}]},
           {intersection,
               [{predef,none},
                {intersection,
                    [{predef,none},
                     {intersection,
                         [{predef,none},{named,0,{ty_ref,'.',t8,0},[]}]}]}]}],
          {fun_full,
              [{predef,none}],
              {intersection,
                  [{predef,none},
                   {fun_full,
                       [{predef,none},
                        {predef,any},
                        {named,0,{ty_ref,'.',t4,0},[]},
                        {named,0,{ty_ref,'.',t2,0},[]},
                        {named,0,{ty_ref,'.',t3,0},[]},
                        {predef,none},
                        {predef,none}],
                       {named,0,{ty_ref,'.',t4,0},[]}}]}}},
  t7 =>
      {fun_full,
          [{union,
               [{intersection,
                    [{union,
                         [{named,0,{ty_ref,'.',t3,0},[]},
                          {named,0,{ty_ref,'.',t5,0},[]}]},
                     {predef,none}]},
                {predef,any}]}],
          {union,
              [{fun_full,
                   [{union,[{predef,none},{named,0,{ty_ref,'.',t8,0},[]}]}],
                   {intersection,
                       [{named,0,{ty_ref,'.',t6,0},[]},{predef,any}]}},
               {union,
                   [{intersection,[{predef,any},{predef,none}]},
                    {union,[{predef,any},{named,0,{ty_ref,'.',t4,0},[]}]}]}]}},
  t6 => {predef,none},
  t8 =>
      {intersection,
          [{predef,any},
           {intersection,
               [{intersection,
                    [{fun_full,[{named,0,{ty_ref,'.',t6,0},[]}],{predef,any}},
                     {fun_full,
                         [{named,0,{ty_ref,'.',t2,0},[]},
                          {named,0,{ty_ref,'.',t5,0},[]},
                          {predef,none},
                          {named,0,{ty_ref,'.',t8,0},[]},
                          {predef,none},
                          {predef,any}],
                         {predef,any}}]},
                {fun_full,
                    [{predef,any}],
                    {intersection,
                        [{predef,none},{named,0,{ty_ref,'.',t1,0},[]}]}}]}]},
  t3 =>
      {fun_full,
          [{union,
               [{intersection,
                    [{named,0,{ty_ref,'.',t9,0},[]},
                     {intersection,[{predef,none},{predef,any}]}]},
                {union,
                    [{predef,any},
                     {fun_full,
                         [{named,0,{ty_ref,'.',t1,0},[]}],
                         {predef,none}}]}]}],
          {union,
              [{union,
                   [{union,[{predef,none},{predef,any}]},
                    {intersection,
                        [{predef,any},{named,0,{ty_ref,'.',t10,0},[]}]}]},
               {fun_full,
                   [{fun_full,[{predef,none}],{predef,none}}],
                   {fun_full,
                       [{named,0,{ty_ref,'.',t2,0},[]}],
                       {predef,none}}}]}},
  t5 =>
      {union,
          [{union,
               [{union,
                    [{union,[{predef,none},{predef,none}]},
                     {fun_full,
                         [{named,0,{ty_ref,'.',t7,0},[]}],
                         {predef,any}}]},
                {intersection,
                    [{intersection,[{predef,none},{predef,any}]},
                     {intersection,[{predef,none},{predef,none}]}]}]},
           {fun_full,
               [{predef,any}],
               {fun_full,
                   [{fun_full,
                        [{predef,none},{predef,none},{predef,any}],
                        {predef,none}}],
                   {fun_full,
                       [{named,0,{ty_ref,'.',t1,0},[]}],
                       {predef,any}}}}]},
  t4 =>
      {union,
          [{fun_full,
               [{union,
                    [{fun_full,
                         [{predef,none},
                          {predef,any},
                          {predef,none},
                          {predef,none},
                          {predef,none},
                          {named,0,{ty_ref,'.',t5,0},[]},
                          {named,0,{ty_ref,'.',t6,0},[]},
                          {predef,any},
                          {predef,none},
                          {predef,none},
                          {predef,none},
                          {named,0,{ty_ref,'.',t4,0},[]},
                          {predef,any},
                          {named,0,{ty_ref,'.',t1,0},[]},
                          {named,0,{ty_ref,'.',t9,0},[]},
                          {predef,any},
                          {predef,none},
                          {predef,any}],
                         {predef,any}},
                     {fun_full,[{predef,any}],{predef,none}}]},
                {predef,any},
                {fun_full,
                    [{intersection,
                         [{predef,none},{named,0,{ty_ref,'.',t3,0},[]}]},
                     {fun_full,[{predef,none}],{named,0,{ty_ref,'.',t8,0},[]}},
                     {named,0,{ty_ref,'.',t3,0},[]},
                     {intersection,
                         [{named,0,{ty_ref,'.',t3,0},[]},{predef,any}]},
                     {named,0,{ty_ref,'.',t3,0},[]},
                     {union,[{named,0,{ty_ref,'.',t5,0},[]},{predef,any}]},
                     {intersection,[{predef,any},{predef,none}]},
                     {union,[{predef,none},{predef,any}]},
                     {predef,none},
                     {union,[{named,0,{ty_ref,'.',t4,0},[]},{predef,none}]},
                     {intersection,
                         [{named,0,{ty_ref,'.',t2,0},[]},
                          {named,0,{ty_ref,'.',t5,0},[]}]},
                     {fun_full,[{predef,any}],{predef,none}},
                     {union,[{predef,none},{predef,none}]},
                     {fun_full,
                         [{named,0,{ty_ref,'.',t9,0},[]},
                          {predef,any},
                          {named,0,{ty_ref,'.',t5,0},[]}],
                         {predef,any}},
                     {intersection,
                         [{named,0,{ty_ref,'.',t9,0},[]},
                          {named,0,{ty_ref,'.',t10,0},[]}]}],
                    {union,[{named,0,{ty_ref,'.',t9,0},[]},{predef,any}]}},
                {union,
                    [{intersection,[{predef,none},{predef,any}]},
                     {union,[{predef,any},{named,0,{ty_ref,'.',t9,0},[]}]}]},
                {predef,any},
                {predef,any},
                {named,0,{ty_ref,'.',t4,0},[]}],
               {fun_full,
                   [{predef,none}],
                   {fun_full,
                       [{named,0,{ty_ref,'.',t8,0},[]}],
                       {named,0,{ty_ref,'.',t4,0},[]}}}},
           {fun_full,
               [{named,0,{ty_ref,'.',t1,0},[]},
                {intersection,
                    [{union,[{predef,any},{named,0,{ty_ref,'.',t7,0},[]}]},
                     {fun_full,
                         [{predef,any}],
                         {named,0,{ty_ref,'.',t8,0},[]}}]},
                {union,[{named,0,{ty_ref,'.',t3,0},[]},{predef,any}]},
                {predef,any},
                {predef,none},
                {fun_full,[{predef,any}],{predef,none}},
                {fun_full,
                    [{fun_full,
                         [{named,0,{ty_ref,'.',t10,0},[]}],
                         {predef,none}}],
                    {fun_full,[{predef,none}],{predef,none}}},
                {fun_full,
                    [{union,[{predef,none},{named,0,{ty_ref,'.',t10,0},[]}]},
                     {intersection,
                         [{named,0,{ty_ref,'.',t4,0},[]},{predef,none}]},
                     {fun_full,[{predef,none}],{predef,none}},
                     {predef,any},
                     {intersection,[{predef,none},{predef,any}]},
                     {predef,none},
                     {intersection,
                         [{named,0,{ty_ref,'.',t6,0},[]},
                          {named,0,{ty_ref,'.',t8,0},[]}]},
                     {predef,any},
                     {intersection,
                         [{named,0,{ty_ref,'.',t1,0},[]},{predef,none}]},
                     {intersection,[{predef,none},{predef,none}]},
                     {fun_full,
                         [{predef,none},
                          {predef,any},
                          {named,0,{ty_ref,'.',t9,0},[]},
                          {predef,any},
                          {predef,none},
                          {named,0,{ty_ref,'.',t10,0},[]},
                          {named,0,{ty_ref,'.',t9,0},[]},
                          {named,0,{ty_ref,'.',t3,0},[]},
                          {named,0,{ty_ref,'.',t4,0},[]},
                          {predef,any},
                          {predef,any},
                          {predef,none},
                          {predef,none},
                          {predef,none},
                          {predef,none},
                          {predef,none}],
                         {predef,any}},
                     {union,[{predef,any},{named,0,{ty_ref,'.',t6,0},[]}]}],
                    {predef,none}},
                {predef,none},
                {fun_full,
                    [{fun_full,
                         [{named,0,{ty_ref,'.',t9,0},[]},
                          {predef,any},
                          {predef,none},
                          {predef,none},
                          {predef,any},
                          {named,0,{ty_ref,'.',t10,0},[]},
                          {named,0,{ty_ref,'.',t4,0},[]},
                          {named,0,{ty_ref,'.',t2,0},[]},
                          {predef,any},
                          {named,0,{ty_ref,'.',t10,0},[]},
                          {predef,none},
                          {predef,none},
                          {predef,any},
                          {predef,any},
                          {predef,none},
                          {named,0,{ty_ref,'.',t3,0},[]},
                          {predef,none}],
                         {predef,none}}],
                    {predef,any}},
                {fun_full,
                    [{named,0,{ty_ref,'.',t7,0},[]},
                     {intersection,
                         [{predef,any},{named,0,{ty_ref,'.',t4,0},[]}]},
                     {union,[{predef,any},{predef,none}]},
                     {intersection,
                         [{named,0,{ty_ref,'.',t2,0},[]},{predef,any}]},
                     {predef,any},
                     {predef,none},
                     {fun_full,
                         [{named,0,{ty_ref,'.',t9,0},[]},
                          {predef,any},
                          {named,0,{ty_ref,'.',t8,0},[]},
                          {predef,any},
                          {predef,none},
                          {named,0,{ty_ref,'.',t5,0},[]},
                          {predef,none},
                          {predef,any},
                          {predef,any},
                          {predef,any}],
                         {predef,any}},
                     {union,[{predef,any},{named,0,{ty_ref,'.',t2,0},[]}]},
                     {fun_full,[{named,0,{ty_ref,'.',t1,0},[]}],{predef,any}}],
                    {predef,any}},
                {union,
                    [{fun_full,[{named,0,{ty_ref,'.',t5,0},[]}],{predef,any}},
                     {union,[{predef,any},{predef,none}]}]},
                {intersection,
                    [{intersection,
                         [{predef,any},{named,0,{ty_ref,'.',t5,0},[]}]},
                     {union,[{predef,none},{named,0,{ty_ref,'.',t6,0},[]}]}]},
                {fun_full,
                    [{union,[{named,0,{ty_ref,'.',t7,0},[]},{predef,none}]}],
                    {union,[{predef,any},{named,0,{ty_ref,'.',t1,0},[]}]}},
                {intersection,
                    [{union,[{predef,none},{predef,any}]},
                     {intersection,
                         [{predef,any},{named,0,{ty_ref,'.',t8,0},[]}]}]},
                {fun_full,
                    [{intersection,
                         [{named,0,{ty_ref,'.',t5,0},[]},
                          {named,0,{ty_ref,'.',t4,0},[]}]}],
                    {fun_full,[{predef,any}],{predef,any}}},
                {fun_full,
                    [{intersection,
                         [{named,0,{ty_ref,'.',t4,0},[]},{predef,any}]}],
                    {predef,none}}],
               {predef,any}}]},
  t10 =>
      {union,
          [{union,[{predef,none},{predef,any}]},
           {intersection,
               [{intersection,
                    [{intersection,[{predef,any},{predef,any}]},
                     {fun_full,
                         [{named,0,{ty_ref,'.',t8,0},[]}],
                         {named,0,{ty_ref,'.',t3,0},[]}}]},
                {intersection,
                    [{predef,any},
                     {fun_full,
                         [{named,0,{ty_ref,'.',t1,0},[]}],
                         {predef,none}}]}]}]}},

  global_state:with_new_state(fun() -> 
    ty_parser:set_symtab(System),
    maps:foreach(fun(VarName, AstTy) ->
      % io:format(user,"~p~n", [AstTy]),
      ty_parser:extend_symtab(VarName, {ty_scheme, [], AstTy})
    end, System),

    Ty1 = {named, noloc, {ty_ref, '.', t1, 0}, []},
    {T1, _Parsed} = timer:tc(fun() -> ty_parser:parse(Ty1) end),
    io:format(user,"~p~n", [T1]),
    {T2, _Parsed} = timer:tc(fun() -> ty_parser:parse(Ty1) end),
    io:format(user,"~p~n", [T2]),
    {T3, _Parsed} = timer:tc(fun() -> ty_parser:parse(Ty1) end),
    io:format(user,"~p~n", [T3]),
    {T4, _Parsed} = timer:tc(fun() -> ty_parser:parse(Ty1) end),
    io:format(user,"~p~n", [T4]),
    {T5, _Parsed} = timer:tc(fun() -> ty_parser:parse(Ty1) end),
    io:format(user,"~p~n", [T5]),
    {T6, _Parsed} = timer:tc(fun() -> ty_parser:parse(Ty1) end),
    io:format(user,"~p~n", [T6]),
    {T7, _Parsed} = timer:tc(fun() -> ty_parser:parse(Ty1) end),
    io:format(user,"~p~n", [T7]),
    {T8, _Parsed} = timer:tc(fun() -> ty_parser:parse(Ty1) end),
    io:format(user,"~p~n", [T8]),
    {T9, _Parsed} = timer:tc(fun() -> ty_parser:parse(Ty1) end),
    io:format(user,"~p~n", [T9]),


    ok
  end).
